import {Router} from 'express';import crypto from 'node:crypto';import {z} from 'zod';import {allow} from '../auth.js';import {Employee,Schedule,TransportRequest} from '../models.js';import {asyncHandler,audit,evaluateEligibility,startOfDay} from '../utils.js';import {notify} from '../realtime.js'
const router=Router(),input=z.object({bms:z.string().regex(/^\d{7}$/),siteCode:z.string().min(2),name:z.string().min(3),email:z.string().email().optional().or(z.literal('')),department:z.string().min(2),supervisor:z.string().nullable().optional(),address:z.object({line1:z.string().min(3),sector:z.string().optional(),city:z.string().default('Santo Domingo'),zone:z.string().min(2)}),active:z.boolean().default(true),generalEligibility:z.boolean().default(true),recurring:z.boolean().default(false)})
router.get('/',asyncHandler(async(req,res)=>{const filter=req.user.role==='supervisor'?{supervisor:req.user._id}:req.user.role==='employee'?{_id:req.user.employee}:{};const data=await Employee.find(filter).populate('supervisor','name email').sort({name:1}).lean();res.json({data:data.map(x=>({...x,employeeCode:x.bms}))})}))
router.post('/',allow('admin','hr','trainer'),asyncHandler(async(req,res)=>{const data=await Employee.create({...input.parse(req.body),qrToken:crypto.randomBytes(24).toString('hex')});await audit(req,'employee.created','Employee',data.id,null,data.toObject());res.status(201).json({data})}))
router.post('/bulk',allow('admin','hr'),asyncHandler(async(req,res)=>{const items=z.array(input).min(1).max(2000).parse(req.body.items),created=[],errors=[];for(let i=0;i<items.length;i++)try{const item=await Employee.create({...items[i],qrToken:crypto.randomBytes(24).toString('hex')});created.push(item)}catch(e){errors.push({row:i+1,bms:items[i].bms,message:e.message})}await audit(req,'employees.imported','Employee','bulk',null,{created:created.length,errors});res.status(errors.length?207:201).json({data:{created,errors}})}))
router.patch('/:id',allow('admin','hr'),asyncHandler(async(req,res)=>{const before=await Employee.findById(req.params.id).lean();if(!before)return res.status(404).json({error:{code:'NOT_FOUND',message:'Empleado no encontrado.'}});const allowed=['name','email','department','supervisor','address','active','generalEligibility','recurring','siteCode'],changes={};for(const key of allowed)if(key in req.body)changes[key]=req.body[key];const data=await Employee.findByIdAndUpdate(req.params.id,{$set:changes},{new:true,runValidators:true});await audit(req,'employee.updated','Employee',data.id,before,data.toObject(),{changedFields:Object.keys(changes)});res.json({data})}))
router.get('/:id/schedules',allow('admin','workforce'),asyncHandler(async(req,res)=>res.json({data:await Schedule.find({employee:req.params.id}).populate('createdBy','name role').sort({workDate:-1}).limit(180).lean()})))
router.put('/:id/schedules/:date',allow('admin','workforce'),asyncHandler(async(req,res)=>{const body=z.object({startsAt:z.string(),endsAt:z.string(),workingDays:z.array(z.number().int().min(0).max(6)),overtimeApproved:z.boolean(),reason:z.string().min(3)}).parse(req.body),date=startOfDay(req.params.date),employee=await Employee.findById(req.params.id);if(!employee)return res.status(404).json({error:{code:'NOT_FOUND',message:'Empleado no encontrado.'}});const before=await Schedule.findOne({employee:employee._id,workDate:date}).lean(),schedule=await Schedule.findOneAndUpdate({employee:employee._id,workDate:date},{employee:employee._id,workDate:date,startsAt:body.startsAt,endsAt:body.endsAt,workingDays:body.workingDays,overtimeApproved:body.overtimeApproved,changeReason:body.reason,source:'manual',createdBy:req.user._id},{upsert:true,new:true,runValidators:true}),eligibility=await evaluateEligibility(employee,schedule),request=await TransportRequest.findOneAndUpdate({employee:employee._id,serviceDate:date},{status:eligibility.eligible?'pending':'rejected',eligibilityReason:eligibility.reason},{upsert:true,new:true});await audit(req,'schedule.updated','Schedule',schedule.id,before,schedule.toObject(),{reason:body.reason});const user=(await import('../models.js')).User;const employeeUser=await user.findOne({employee:employee._id});if(employeeUser)await notify({user:employeeUser._id,type:'schedule_changed',title:'Horario actualizado',message:body.reason,entityType:'Schedule',entityId:schedule.id});res.json({data:{schedule,request,eligibility}})}))
router.post('/schedules/bulk',allow('admin','workforce'),asyncHandler(async(req,res)=>{const rows=z.array(z.object({bms:z.string().regex(/^\d{7}$/),workDate:z.coerce.date(),startsAt:z.string(),endsAt:z.string(),workingDays:z.array(z.number().int()).default([]),overtimeApproved:z.boolean().default(false),reason:z.string().min(3)})).min(1).max(5000).parse(req.body.rows),results=[];for(const row of rows){const employee=await Employee.findOne({bms:row.bms});if(!employee){results.push({bms:row.bms,status:'error',message:'BMS no encontrado'});continue}const date=startOfDay(row.workDate),before=await Schedule.findOne({employee:employee._id,workDate:date}).lean(),schedule=await Schedule.findOneAndUpdate({employee:employee._id,workDate:date},{...row,employee:employee._id,workDate:date,source:'import',changeReason:row.reason,createdBy:req.user._id},{upsert:true,new:true});await audit(req,'schedule.imported','Schedule',schedule.id,before,schedule.toObject(),{reason:row.reason});results.push({bms:row.bms,status:'ok'})}res.status(201).json({data:results})}))
router.get('/:id/history',asyncHandler(async(req,res)=>res.json({data:await TransportRequest.find({employee:req.params.id}).populate({path:'route',populate:['vehicle','driver']}).sort({serviceDate:-1}).limit(50).lean()})))
export default router
