import {Router} from 'express';import {z} from 'zod';import {allow} from '../auth.js';import {AuditLog,Boarding,Employee,Notification,Route,TransportRequest,Trip,User} from '../models.js';import {asyncHandler,audit} from '../utils.js'
const router=Router()
router.post('/requests/:id/decision',allow('supervisor','admin'),asyncHandler(async(req,res)=>{const input=z.object({decision:z.enum(['approved','rejected']),comment:z.string().min(3)}).parse(req.body),before=await TransportRequest.findById(req.params.id).lean();if(!before)return res.status(404).json({error:{code:'NOT_FOUND',message:'Solicitud no encontrada.'}});const data=await TransportRequest.findByIdAndUpdate(req.params.id,{approvalStatus:input.decision,status:input.decision==='approved'?'confirmed':'rejected',supervisorComment:input.comment,approvedBy:req.user._id,decidedAt:new Date()},{new:true});const user=await User.findOne({employee:data.employee});if(user)await Notification.create({user:user._id,type:`exception_${input.decision}`,title:`Excepción ${input.decision==='approved'?'aprobada':'rechazada'}`,message:input.comment,entityType:'TransportRequest',entityId:data.id});await audit(req,`request.${input.decision}`,'TransportRequest',data.id,before,data.toObject());res.json({data})}))
router.post('/routes/:id/start',allow('driver'),asyncHandler(async(req,res)=>{const route=await Route.findById(req.params.id);if(!route)return res.status(404).json({error:{code:'NOT_FOUND',message:'Ruta no encontrada.'}});const boarded=await Boarding.countDocuments({route:route._id,validation:{$in:['allowed','ad_hoc']}}),missing=Math.max(0,route.passengers.length-boarded),input=z.object({confirmMissing:z.boolean().default(false)}).parse(req.body);if(missing&&!input.confirmMissing)return res.status(409).json({error:{code:'PASSENGERS_PENDING',message:`Faltan ${missing} pasajeros por abordar.`,details:{missing}}});const trip=await Trip.create({route:route._id,startedBy:req.user._id,missingPassengers:missing});route.status='boarding';await route.save();await Notification.create({user:req.user._id,type:'trip_started',title:'Viaje iniciado',message:`${route.code} inició con ${missing} pendientes.`,entityType:'Trip',entityId:trip.id});await audit(req,'trip.started','Trip',trip.id,null,trip.toObject());res.status(201).json({data:trip})}))
router.get('/notifications',asyncHandler(async(req,res)=>res.json({data:await Notification.find({user:req.user._id}).sort({createdAt:-1}).limit(100).lean()})))
router.post('/notifications/:id/read',asyncHandler(async(req,res)=>res.json({data:await Notification.findOneAndUpdate({_id:req.params.id,user:req.user._id},{readAt:new Date()},{new:true})})))
router.get('/audit',allow('admin'),asyncHandler(async(req,res)=>res.json({data:await AuditLog.find().populate('actor','name email role').sort({createdAt:-1}).limit(500).lean()})))
router.get('/reports/summary',allow('admin','operations','hr','supervisor'),asyncHandler(async(req,res)=>{const [requests,routes,boarded,adHoc]=await Promise.all([TransportRequest.countDocuments(),Route.countDocuments(),Boarding.countDocuments({validation:'allowed'}),Boarding.countDocuments({validation:'ad_hoc'})]);res.json({data:{requests,routes,boarded,adHoc,generatedAt:new Date()}})}))
export default router
