import {Router} from 'express';import {z} from 'zod';import {allow} from '../auth.js';import {Employee,EligibilityRule,TransportRequest,User} from '../models.js';import {asyncHandler,audit,startOfDay} from '../utils.js';import {notify} from '../realtime.js'
const router=Router()
async function windowFor(date){const rule=await EligibilityRule.findOne({key:'confirmation_deadline',enabled:true}).lean(),deadline=rule?.value||'21:00',[h,m]=deadline.split(':').map(Number),cutoff=new Date(date);cutoff.setHours(h,m,0,0);return{canModify:new Date()<=cutoff,deadline,cutoff}}
router.get('/',asyncHandler(async(req,res)=>{const filter={};if(req.user.role==='employee')filter.employee=req.user.employee;if(req.user.role==='supervisor')filter.employee={$in:await Employee.find({supervisor:req.user._id}).distinct('_id')};const data=await TransportRequest.find(filter).populate('employee','bms name department address supervisor').populate('route','code name departureTime vehicle').sort({serviceDate:-1}).limit(500).lean();res.json({data:await Promise.all(data.map(async x=>({...x,...await windowFor(x.serviceDate)})))})}))
async function own(req,id){const data=await TransportRequest.findById(id);if(!data)return null;if(req.user.role==='employee'&&String(data.employee)!==String(req.user.employee))return false;return data}
async function ensureOpen(res,data){const w=await windowFor(data.serviceDate);if(!w.canModify){res.status(409).json({error:{code:'CONFIRMATION_CLOSED',message:`El límite de confirmación (${w.deadline}) ya cerró.`}});return false}return true}
router.post('/:id/confirm',allow('employee'),asyncHandler(async(req,res)=>{const data=await own(req,req.params.id);if(data===false)return res.status(403).json({error:{code:'FORBIDDEN',message:'Solicitud ajena.'}});if(!data)return res.status(404).json({error:{code:'NOT_FOUND',message:'Solicitud no encontrada.'}});if(!await ensureOpen(res,data))return;const before=data.toObject();data.status='confirmed';data.confirmedAt=new Date();await data.save();await audit(req,'request.confirmed','TransportRequest',data.id,before,data.toObject());await notify({user:req.user._id,type:'transport_confirmed',title:'Transporte confirmado',message:'Tu lugar fue reservado.',entityType:'TransportRequest',entityId:data.id});res.json({data:{...data.toObject(),...await windowFor(data.serviceDate)}})}))
router.post('/:id/cancel',allow('employee'),asyncHandler(async(req,res)=>{const data=await own(req,req.params.id);if(!data||data===false)return res.status(data===false?403:404).json({error:{code:data===false?'FORBIDDEN':'NOT_FOUND',message:'Solicitud no disponible.'}});if(!await ensureOpen(res,data))return;const before=data.toObject();data.status='cancelled';data.confirmedAt=null;await data.save();await audit(req,'request.cancelled','TransportRequest',data.id,before,data.toObject());res.json({data:{...data.toObject(),...await windowFor(data.serviceDate)}})}))
router.post('/exception',allow('employee'),asyncHandler(async(req,res)=>{const body=z.object({serviceDate:z.coerce.date(),reason:z.enum(['overtime','shift_change','emergency','extraordinary']),comment:z.string().min(10)}).parse(req.body),employee=await Employee.findById(req.user.employee);if(!employee)return res.status(404).json({error:{code:'NOT_FOUND',message:'Perfil no encontrado.'}});const date=startOfDay(body.serviceDate),data=await TransportRequest.findOneAndUpdate({employee:employee._id,serviceDate:date},{employee:employee._id,serviceDate:date,status:'pending',exceptional:true,exceptionReason:body.reason==='shift_change'?'operational_change':body.reason==='extraordinary'?'substitution':body.reason,employeeComment:body.comment,approvalStatus:'pending'},{upsert:true,new:true});await audit(req,'request.exception_created','TransportRequest',data.id,null,data.toObject());if(employee.supervisor)await notify({user:employee.supervisor,type:'exception_pending',title:'Excepción pendiente',message:`${employee.name}: ${body.comment}`,entityType:'TransportRequest',entityId:data.id});res.status(201).json({data})}))
router.post('/:id/decision',allow('supervisor','admin'),asyncHandler(async(req,res)=>{const body=z.object({decision:z.enum(['approved','rejected']),comment:z.string().min(3)}).parse(req.body),data=await TransportRequest.findById(req.params.id).populate('employee');if(!data)return res.status(404).json({error:{code:'NOT_FOUND',message:'Solicitud no encontrada.'}});if(req.user.role==='supervisor'&&String(data.employee.supervisor)!==String(req.user._id))return res.status(403).json({error:{code:'FORBIDDEN',message:'Empleado fuera de tu equipo.'}});const before=data.toObject();data.approvalStatus=body.decision;data.status=body.decision==='approved'?'confirmed':'rejected';data.supervisorComment=body.comment;data.approvedBy=req.user._id;data.decidedAt=new Date();await data.save();await audit(req,`request.${body.decision}`,'TransportRequest',data.id,before,data.toObject());const employeeUser=await User.findOne({employee:data.employee._id});if(employeeUser)await notify({user:employeeUser._id,type:`exception_${body.decision}`,title:`Excepción ${body.decision==='approved'?'aprobada':'rechazada'}`,message:body.comment,entityType:'TransportRequest',entityId:data.id});res.json({data})}))
export default router
