import {Router} from 'express';import {z} from 'zod';import {allow} from '../auth.js';import {Employee,Route,TransportRequest,User,Vehicle} from '../models.js';import {asyncHandler,audit,startOfDay} from '../utils.js';import {notify} from '../realtime.js'
const router=Router(),write=allow('operations','admin'),schema=z.object({code:z.string().min(2),name:z.string().min(3),description:z.string().default(''),routeType:z.enum(['door_to_door','common_points']),serviceDate:z.coerce.date(),zone:z.string(),departureTime:z.string(),estimatedMinutes:z.number().int().positive(),vehicle:z.string(),driver:z.string().nullable().optional(),passengers:z.array(z.string()).default([]),stops:z.array(z.object({label:z.string().min(2),order:z.number().int().min(0)})).default([])})
router.get('/',asyncHandler(async(req,res)=>{const date=startOfDay(req.query.date);res.json({data:await Route.find({serviceDate:date}).populate('vehicle').populate('driver').populate('passengers','bms name department address').sort({code:1}).lean()})}))
router.post('/',write,asyncHandler(async(req,res)=>{const body=schema.parse(req.body),vehicle=await Vehicle.findById(body.vehicle);if(!vehicle)return res.status(400).json({error:{code:'INVALID_VEHICLE',message:'Vehículo no disponible.'}});if(body.passengers.length>vehicle.capacity)return res.status(409).json({error:{code:'CAPACITY_EXCEEDED',message:'La ruta supera la capacidad del vehículo.'}});const data=await Route.create({...body,serviceDate:startOfDay(body.serviceDate)});await assign(data,body.passengers,req);await audit(req,'route.created','Route',data.id,null,data.toObject());res.status(201).json({data})}))
router.patch('/:id',write,asyncHandler(async(req,res)=>{const before=await Route.findById(req.params.id).lean();if(!before)return res.status(404).json({error:{code:'NOT_FOUND',message:'Ruta no encontrada.'}});const allowed=['name','description','routeType','zone','departureTime','estimatedMinutes','vehicle','driver','stops'],changes={};for(const k of allowed)if(k in req.body)changes[k]=req.body[k];const data=await Route.findByIdAndUpdate(req.params.id,{$set:changes},{new:true,runValidators:true});await audit(req,'route.updated','Route',data.id,before,data.toObject());res.json({data})}))
router.delete('/:id',write,asyncHandler(async(req,res)=>{const before=await Route.findById(req.params.id).lean();if(!before)return res.status(404).json({error:{code:'NOT_FOUND',message:'Ruta no encontrada.'}});await TransportRequest.updateMany({route:req.params.id},{$unset:{route:1},$set:{status:'confirmed'}});await Route.deleteOne({_id:req.params.id});await audit(req,'route.deleted','Route',req.params.id,before,null);res.status(204).end()}))
router.put('/:id/passengers',write,asyncHandler(async(req,res)=>{const passengers=z.array(z.string()).parse(req.body.passengers),data=await Route.findById(req.params.id).populate('vehicle');if(!data)return res.status(404).json({error:{code:'NOT_FOUND',message:'Ruta no encontrada.'}});if(passengers.length>data.vehicle.capacity)return res.status(409).json({error:{code:'CAPACITY_EXCEEDED',message:'Capacidad excedida.'}});const before=data.toObject();data.passengers=passengers;await data.save();await assign(data,passengers,req);await audit(req,'route.passengers_updated','Route',data.id,before,data.toObject());res.json({data})}))
router.post('/:id/approve',write,asyncHandler(async(req,res)=>{const before=await Route.findById(req.params.id).lean(),data=await Route.findByIdAndUpdate(req.params.id,{status:'approved',approvedBy:req.user._id,approvedAt:new Date()},{new:true});if(!data)return res.status(404).json({error:{code:'NOT_FOUND',message:'Ruta no encontrada.'}});await audit(req,'route.approved','Route',data.id,before,data.toObject());res.json({data})}))
async function assign(route,passengers,req){await TransportRequest.updateMany({serviceDate:route.serviceDate,route:route._id,employee:{$nin:passengers}},{$unset:{route:1},$set:{status:'confirmed'}});await TransportRequest.updateMany({serviceDate:route.serviceDate,employee:{$in:passengers}},{$set:{route:route._id,status:'assigned'}});for(const employee of await Employee.find({_id:{$in:passengers}})){const user=await User.findOne({employee:employee._id});if(user)await notify({user:user._id,type:'route_assigned',title:'Ruta asignada',message:`${route.code} · salida ${route.departureTime}`,entityType:'Route',entityId:route.id})}}
export default router
