import test,{after,before} from 'node:test'
import assert from 'node:assert/strict'
import request from 'supertest'
import {createApp} from '../app.js'
import {connectDatabase,disconnectDatabase} from '../db.js'
import bcrypt from 'bcryptjs'
import {Employee,Tenant,TransportRequest,User} from '../models.js'

let app,token,driverToken,adminToken,employeeToken,supervisorToken,routeId,requestId
before(async()=>{await connectDatabase();app=createApp()})
after(async()=>{await disconnectDatabase()})

test('health check responde',async()=>{const res=await request(app).get('/api/health');assert.equal(res.status,200);assert.equal(res.body.status,'ok')})
test('rechaza endpoints privados sin token',async()=>{const res=await request(app).get('/api/dashboard');assert.equal(res.status,401);assert.equal(res.body.error.code,'AUTH_REQUIRED')})
test('operaciones inicia sesión',async()=>{const res=await request(app).post('/api/auth/login').send({tenant:'caribe',email:'operaciones@via.local',password:'ViaDemo2026!'});assert.equal(res.status,200);assert.ok(res.body.token);assert.equal(res.body.user.role,'operations');token=res.body.token})
test('dashboard retorna métricas persistidas',async()=>{const res=await request(app).get('/api/dashboard').set('Authorization',`Bearer ${token}`);assert.equal(res.status,200);assert.ok(Array.isArray(res.body.data.routes));assert.equal(typeof res.body.data.metrics.confirmed,'number')})
test('RBAC impide que operaciones cree empleados',async()=>{const res=await request(app).post('/api/employees').set('Authorization',`Bearer ${token}`).send({});assert.equal(res.status,403);assert.equal(res.body.error.code,'FORBIDDEN')})
test('roles críticos autentican dentro del tenant',async()=>{for(const [email,key] of [['conductor@via.local','driver'],['admin@via.local','admin'],['empleado@via.local','employee'],['supervisor@via.local','supervisor']]){const res=await request(app).post('/api/auth/login').send({tenant:'caribe',email,password:'ViaDemo2026!'});assert.equal(res.status,200);if(key==='driver')driverToken=res.body.token;if(key==='admin')adminToken=res.body.token;if(key==='employee')employeeToken=res.body.token;if(key==='supervisor')supervisorToken=res.body.token}})
test('administrador no puede abordar',async()=>{const dash=await request(app).get('/api/dashboard').set('Authorization',`Bearer ${adminToken}`);routeId=dash.body.data.routes[0]._id;const res=await request(app).post('/api/boarding/scan').set('Authorization',`Bearer ${adminToken}`).send({routeId,bms:'7001042'});assert.equal(res.status,403)})
test('conductor aborda y bloquea duplicado',async()=>{let res=await request(app).post('/api/boarding/scan').set('Authorization',`Bearer ${driverToken}`).send({routeId,bms:'7001042'});assert.equal(res.status,201);assert.equal(res.body.data.validation,'allowed');res=await request(app).post('/api/boarding/scan').set('Authorization',`Bearer ${driverToken}`).send({routeId,bms:'7001042'});assert.equal(res.status,409);assert.equal(res.body.data.validation,'duplicate')})
test('empleado solicita excepción con comentario y supervisor decide',async()=>{let res=await request(app).post('/api/requests/exception').set('Authorization',`Bearer ${employeeToken}`).send({serviceDate:new Date().toISOString(),reason:'emergency',comment:'Emergencia familiar que requiere transporte'});assert.equal(res.status,201);requestId=res.body.data._id;res=await request(app).post(`/api/requests/${requestId}/decision`).set('Authorization',`Bearer ${supervisorToken}`).send({decision:'approved',comment:'Aprobada por emergencia documentada'});assert.equal(res.status,200);assert.equal(res.body.data.approvalStatus,'approved')})
test('inicio de viaje exige confirmación si faltan pasajeros',async()=>{let res=await request(app).post(`/api/pilot/routes/${routeId}/start`).set('Authorization',`Bearer ${driverToken}`).send({confirmMissing:false});assert.equal(res.status,409);assert.equal(res.body.error.code,'PASSENGERS_PENDING');res=await request(app).post(`/api/pilot/routes/${routeId}/start`).set('Authorization',`Bearer ${driverToken}`).send({confirmMissing:true});assert.equal(res.status,201);assert.ok(res.body.data.startedAt)})
test('aislamiento multitenant bloquea datos de otra empresa',async()=>{const tenant=await Tenant.create({name:'Empresa Norte',slug:'norte',sites:[{code:'NTE-01',name:'Norte'}]}),passwordHash=await bcrypt.hash('ViaDemo2026!',10);await User.create({tenant:tenant._id,name:'Operador Norte',email:'operaciones@norte.local',passwordHash,role:'operations'});const login=await request(app).post('/api/auth/login').send({tenant:'norte',email:'operaciones@norte.local',password:'ViaDemo2026!'});assert.equal(login.status,200);const routes=await request(app).get('/api/routes').set('Authorization',`Bearer ${login.body.token}`);assert.equal(routes.status,200);assert.equal(routes.body.data.length,0);const foreign=await request(app).patch(`/api/routes/${routeId}`).set('Authorization',`Bearer ${login.body.token}`).send({name:'Acceso indebido'});assert.equal(foreign.status,404)})
test('límite temporal bloquea cambios tardíos',async()=>{const user=await User.findOne({email:'empleado@via.local'}),employee=await Employee.findById(user.employee),date=new Date();date.setDate(date.getDate()-1);date.setHours(0,0,0,0);const item=await TransportRequest.create({tenant:user.tenant,employee:employee._id,serviceDate:date,status:'confirmed',eligibilityReason:'Prueba límite'});const res=await request(app).post(`/api/requests/${item._id}/cancel`).set('Authorization',`Bearer ${employeeToken}`);assert.equal(res.status,409);assert.equal(res.body.error.code,'CONFIRMATION_CLOSED')})
test('plantillas Excel y reporte están disponibles',async()=>{let res=await request(app).get('/api/templates/employees.xlsx').set('Authorization',`Bearer ${adminToken}`);assert.equal(res.status,200);assert.match(res.headers['content-type'],/spreadsheet/);assert.ok(Number(res.headers['content-length'])>1000);res=await request(app).get('/api/reports/summary.xlsx').set('Authorization',`Bearer ${adminToken}`);assert.equal(res.status,200);assert.ok(Number(res.headers['content-length'])>1000)})
